# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/leds.xdc

# Block Designs: bd/ug1165_bd/ug1165_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd || ORIG_REF_NAME==ug1165_bd}]

# IP: bd/ug1165_bd/ip/ug1165_bd_processing_system7_0_0/ug1165_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_processing_system7_0_0 || ORIG_REF_NAME==ug1165_bd_processing_system7_0_0}]

# IP: bd/ug1165_bd/ip/ug1165_bd_Blink_0_0/ug1165_bd_Blink_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_Blink_0_0 || ORIG_REF_NAME==ug1165_bd_Blink_0_0}]

# IP: bd/ug1165_bd/ip/ug1165_bd_ps7_0_axi_periph_0/ug1165_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==ug1165_bd_ps7_0_axi_periph_0}]

# IP: bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==ug1165_bd_rst_ps7_0_100M_0}]

# IP: bd/ug1165_bd/ip/ug1165_bd_xbar_0/ug1165_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_xbar_0 || ORIG_REF_NAME==ug1165_bd_xbar_0}]

# IP: bd/ug1165_bd/ip/ug1165_bd_auto_pc_0/ug1165_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ug1165_bd_auto_pc_0 || ORIG_REF_NAME==ug1165_bd_auto_pc_0}]

# XDC: bd/ug1165_bd/ug1165_bd_ooc.xdc
