/*  blink.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("blink - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "blink"
// S_AXI_INTR interface OFFSET
#define INTR_OFFSET 0x10000

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

void __iomem *blink_base_addr;
void __iomem *blink_intr_base_addr;

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct blink_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t blink_irq(int irq, void *lp)
{
	printk("blink interrupt\n");
	return IRQ_HANDLED;
}

static int blink_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct blink_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct blink_local *) kmalloc(sizeof(struct blink_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate blink device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	blink_base_addr = lp->base_addr;
	blink_intr_base_addr = lp->base_addr + INTR_OFFSET;
	if (!lp->base_addr) {
		dev_err(dev, "blink: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "blink at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &blink_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"blink at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	blink_base_addr = NULL;
	blink_intr_base_addr = NULL;
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int blink_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct blink_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	blink_base_addr      = NULL;
	blink_intr_base_addr = NULL;
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id blink_of_match[] = {
	{ .compatible = "vendor,blink", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, blink_of_match);
#else
# define blink_of_match
#endif


static struct platform_driver blink_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= blink_of_match,
	},
	.probe		= blink_probe,
	.remove		= blink_remove,
};

// **********sysfs start*********
// show the counter enable register, slv_reg0
static ssize_t blink_counter_enable_show(struct device *dev,
					 struct device_attribute *attr,
					 char *buf)
{
  return snprintf(buf, PAGE_SIZE, "%d\n", ioread32(blink_base_addr));
}

// set the counter enable register, slv_reg0
static ssize_t blink_counter_enable_store(struct device *dev,
					  struct device_attribute *attr,
					  const char *buf,
					  size_t count)
{
  int tmp;
  sscanf(buf, "%d", &tmp);

  if( (tmp < 0) || (tmp == 0) ){
    tmp = 0;
  }
  else if (tmp >=1){
    tmp = 1;
  }
                        
  iowrite32(unsigned int(tmp), blink_base_addr);

  return count;
}

// show the global interrupt enable register, reg_global_intr_en
static ssize_t blink_global_intr_enable_show(struct device *dev,
					     struct device_attribute *attr,
					     char *buf)
{
  return snprintf(buf, PAGE_SIZE, "%d\n", ioread32(blink_intr_base_addr));
}

// set the global interrupt enable register, reg_global_intr_en
static ssize_t blink_global_intr_enable_store(struct device *dev,
					      struct device_attribute *attr,
					      const char *buf,
					      size_t count)
{
  int tmp;
  sscanf(buf, "%d", &tmp);

  if( (tmp < 0) || (tmp == 0) ){
    tmp = 0;
  }
  else if (tmp >=1){
    tmp = 1;
  }
                        
  iowrite32(usigned int(tmp), blink_intr_base_addrr);

  return count;
}

// show the interrupt enable register, reg_intr_en
static ssize_t blink_intr_enable_show(struct device *dev,
				      struct device_attribute *attr,
				      char *buf)
{
  return snprintf(buf, PAGE_SIZE, "%d\n", ioread32(blink_intr_base_addr+4));
}

// set the interrupt enable register, reg_intr_en
static ssize_t blink_intr_enable_store(struct device *dev,
				       struct device_attribute *attr,
				       const char *buf,
				       size_t count)
{
  int tmp;
  sscanf(buf, "%d", &tmp);

  if( (tmp < 0) || (tmp == 0) ){
    tmp = 0;
  }
  else if (tmp >=1){
    tmp = 1;
  }
                        
  iowrite32(usigned int(tmp), blink_intr_base_addr+4);

  return count;
}

// set the interrupt acknowledgement register, reg_intr_ack
static ssize_t blink_intr_ack_store(struct device *dev,
				       struct device_attribute *attr,
				       const char *buf,
				       size_t count)
{
  int tmp;
  sscanf(buf, "%d", &tmp);

  if( (tmp < 0) || (tmp == 0) ){
    tmp = 0;
  }
  else if (tmp >=1){
    tmp = 1;
  }
                        
  iowrite32(usigned int(tmp), blink_intr_base_addr+12);

  return count;
}

static DRIVER_ATTR(blink_counter_enable    , S_IRUSR | S_IWUSR, blink_counter_enable_show    , blink_counter_enable_store    );
static DRIVER_ATTR(blink_global_intr_enable, S_IRUSR | S_IWUSR, blink_global_intr_enable_show, blink_global_intr_enable_store);
static DRIVER_ATTR(blink_intr_enable       , S_IRUSR | S_IWUSR, blink_intr_enable_show       , blink_intr_enable_store       );
static DRIVER_ATTR(blink_intr_ack          , S_IRUSR          , blink_intr_ack_show          , NULL                          );

// *********sysfs end*********

static int __init blink_init(void)
{
  int ret;
  printk("<1>Hello module world.\n");
  printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	 mystr);

  ret = platform_driver_register(&blink_driver);
  if (ret < 0){
    goto fail_driver_register;
  }

  ret = driver_create_file(&blink_driver,
			   &dev_attr_blink_counter_enable);
  if (ret < 0){
    printk(KERN_ERR DRIVER_NAME " cant create device attribute %s %s\n", 
	   DRIVER_NAME, dev_attr_blink_counter_enable.attr.name);
  }

  ret = driver_create_file(&blink_driver,
			   &dev_attr_blink_global_intr_enable);
  if (ret < 0){
    printk(KERN_ERR DRIVER_NAME " cant create device attribute %s %s\n", 
	   DRIVER_NAME, dev_attr_blink_global_intr_enable.attr.name);
  }

  ret = driver_create_file(&blink_driver,
			   &dev_attr_blink_intr_enable);
  if (ret < 0){
    printk(KERN_ERR DRIVER_NAME " cant create device attribute %s %s\n", 
	   DRIVER_NAME, dev_attr_blink_intr_enable.attr.name);
  }

  ret = driver_create_file(&blink_driver,
			   &dev_attr_blink_intr_ack);
  if (ret < 0){
    printk(KERN_ERR DRIVER_NAME " cant create device attribute %s %s\n", 
	   DRIVER_NAME, dev_attr_blink_intr_ack.attr.name);
  }

  return 0;

fail_driver_register:
  return ret;  
}


static void __exit blink_exit(void)
{
	platform_driver_unregister(&blink_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(blink_init);
module_exit(blink_exit);
