# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'ug1165_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0.xci
# IP: The module: 'ug1165_bd_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/zhang/Documents/SoC/ug1165/ug1165.srcs/sources_1/bd/ug1165_bd/ip/ug1165_bd_rst_ps7_0_100M_0/ug1165_bd_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ug1165_bd_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
